config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  
  resources :chatrooms do
    resources :comments
  end

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :chatrooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_chatroom, only: :create
  def create
    comment = Comment.create!(content: params[:comment][:content], chatroom: @chatroom, user: @current_user)
  end

  private
  
  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern
  
  included do
    before_action :ensure_authenticated_user
  end

  private

  def ensure_authenticated_user
    authenticate_user(cookies.signed[:user_id]) || redirect_to(root_path)
  end

  def authenticate_user(user_id)
    if authenticated_user = User.find(user_id)
      cookies.signed[:user_id] ||= user_id
      @current_user = authenticated_user
    end
  end
  
  def unauthenticate_user
    @current_user = nil
    cookies.delete(:user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :ensure_authenticated_user, only: :index

  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_authenticated_user, only: :create
  
  def create
    authenticate_user(params[:user_id])
    redirect_to chatrooms_url 
  end

  def destroy
    unauthenticate_user
    redirect_to root_path  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<h1> Chatrooms </h1>

<ul>
  <% @chatrooms.each do |chatroom| %>
    <li> <%= link_to chatroom.title, chatroom_path(chatroom) %>  </li>
  <% end %>
</ul>

app/views/chatrooms/show.html.erb
<h6> Logged in as <%= @current_user.username %> </h6>
<h1> <%= @chatroom.title %> </h1>
<%= render 'comments/comments', chatroom: @chatroom %>

app/views/comments/_comment.html.erb
<article id = 'comments'>
  <p> <b><%= "#{comment.user.username}: " %> </b><%= comment.content %></p>
</article>

app/views/comments/_comments.html.erb
<section id = 'comments'>
  <%= render chatroom.comments %>
</section>

<%= render 'comments/new', chatroom: chatroom %>

app/views/comments/_new.html.erb
<%= form_for [ chatroom, Comment.new ], remote: true do |form| %>
  <%= form.text_area :content, rows: '10', cols: '60' %><br>
  <%= form.submit 'Post comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1> Authenticate as one of the following users to start chatting </h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username.capitalize, session_path(user_id: user.id), method: :post %> </li>
  <% end %>
</ul>    